-- MySQL Script generated by MySQL Workbench
-- Qui 12 Mai 2016 16:08:31 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `email` VARCHAR(50) NOT NULL,
  `nascimento` DATE NULL,
  `cpf` VARCHAR(20) NULL,
  `nome` VARCHAR(50) NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DadosMes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DadosMes` (
  `mes` DATE NOT NULL,
  `usersEmail` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`mes`, `usersEmail`),
  UNIQUE INDEX `mes_UNIQUE` (`mes` ASC),
  INDEX `fk_dadosMes_Users_idx` (`usersEmail` ASC),
  CONSTRAINT `fk_dadosMes_Users`
    FOREIGN KEY (`usersEmail`)
    REFERENCES `mydb`.`Users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movimentacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movimentacoes` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movimentacao` (
  `categoria` ENUM('RECEITA1', 'RECEITA2') NOT NULL,
  `DadosMes_mes` DATE NOT NULL,
  `DadosMes_usersEmail` VARCHAR(50) NOT NULL,
  `valor` MEDIUMTEXT NULL,
  `despesa` TINYINT(1) NULL,
  PRIMARY KEY (`categoria`, `DadosMes_mes`, `DadosMes_usersEmail`),
  UNIQUE INDEX `categoria_UNIQUE` (`categoria` ASC),
  INDEX `fk_Movimentacao_DadosMes1_idx` (`DadosMes_mes` ASC, `DadosMes_usersEmail` ASC),
  CONSTRAINT `fk_Movimentacao_DadosMes1`
    FOREIGN KEY (`DadosMes_mes` , `DadosMes_usersEmail`)
    REFERENCES `mydb`.`DadosMes` (`mes` , `usersEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
