/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import model.Calendario;

/**
 *
 * @author Eliezer
 */
public class ViewMenuPopUp extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenuPopUp
     */
    public ViewMenuPopUp() {
        initComponents();
    }
    
    public void addController(ActionListener c) {
        popupOk.addActionListener(c);
        popupCancelar.addActionListener(c);
    }
    
    public void popularMenus() {
        popupMesCb.setModel(new DefaultComboBoxModel(Calendario.listaMes));
        popupAnoCb.setModel(new DefaultComboBoxModel(Calendario.listaAno));
    }
    
    public String getMesPopup() {
        return (String)popupMesCb.getSelectedItem();
    }
    
    public String getAnoPopup() {
        return (String)popupAnoCb.getSelectedItem();
    }
    
    public String getCommand() {
        return this.command;
    }
    
    public void setCommand(String comm) {
        this.command = comm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMesCb = new javax.swing.JComboBox<>();
        popupAnoCb = new javax.swing.JComboBox<>();
        popupOk = new javax.swing.JButton();
        popupCancelar = new javax.swing.JButton();
        popupSelecioneLabel = new javax.swing.JLabel();

        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        popupMesCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro" }));

        popupAnoCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016" }));

        popupOk.setText("OK");
        popupOk.setActionCommand("popupOk");
        popupOk.setName(""); // NOI18N

        popupCancelar.setText("CANCELAR");
        popupCancelar.setActionCommand("popupCancelar");

        popupSelecioneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        popupSelecioneLabel.setText("Selecione Mês e Ano.");
        popupSelecioneLabel.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(popupSelecioneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(popupMesCb, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(popupOk, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(popupCancelar))
                            .addComponent(popupAnoCb, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(popupSelecioneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(popupMesCb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(popupAnoCb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popupOk)
                    .addComponent(popupCancelar))
                .addGap(11, 11, 11))
        );

        popupOk.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String command;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> popupAnoCb;
    private javax.swing.JButton popupCancelar;
    private javax.swing.JComboBox<String> popupMesCb;
    private javax.swing.JButton popupOk;
    private javax.swing.JLabel popupSelecioneLabel;
    // End of variables declaration//GEN-END:variables
}
