/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Eliezer
 */

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionListener;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.util.Rotation;


public class ViewRelatorios extends javax.swing.JFrame {

    /**
     * Creates new form ViewRelatorios
     */
    
    public ViewRelatorios() {
        initComponents();
        geraPieChart(7);
        geraBarChart();
    }
    
    public void addController(ActionListener c) {
        relatorioVoltar.addActionListener(c);
        relatorioVoltar2.addActionListener(c);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewRelatorio_Pie = new javax.swing.JPanel();
        relatorioMesTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        relatorioMesInicialCb = new javax.swing.JComboBox<>();
        relatorioMesFinalCb = new javax.swing.JComboBox<>();
        relatorioCategoriaCb = new javax.swing.JComboBox<>();
        relatorioVoltar = new javax.swing.JButton();
        viewRelatorio_Bar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        viewRelatorio_BarChart = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        relatorioCategoriaMesCb = new javax.swing.JComboBox<>();
        relatorioVoltar2 = new javax.swing.JButton();
        viewRelatorio_PieChart = new javax.swing.JLayeredPane();

        viewRelatorio_Pie.setLayout(new java.awt.BorderLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        relatorioMesInicialCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        relatorioMesFinalCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        relatorioCategoriaCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        relatorioVoltar.setText("Voltar");
        relatorioVoltar.setActionCommand("relatorioVoltar");

        viewRelatorio_Bar.setBackground(getBackground());
        viewRelatorio_Bar.setLayout(new java.awt.BorderLayout());

        viewRelatorio_BarChart.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewRelatorio_BarChart)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewRelatorio_BarChart)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(relatorioMesFinalCb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(relatorioCategoriaCb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(relatorioMesInicialCb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(relatorioVoltar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10)
                                .addComponent(viewRelatorio_Bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(relatorioMesInicialCb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relatorioMesFinalCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(relatorioCategoriaCb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewRelatorio_Bar, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(relatorioVoltar)
                .addContainerGap())
        );

        relatorioMesTab.addTab("tab1", jPanel1);

        relatorioCategoriaMesCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        relatorioVoltar2.setText("Voltar");
        relatorioVoltar2.setActionCommand("relatorioVoltar");

        viewRelatorio_PieChart.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(relatorioVoltar2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(relatorioCategoriaMesCb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 220, Short.MAX_VALUE))
                    .addComponent(viewRelatorio_PieChart))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(relatorioCategoriaMesCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewRelatorio_PieChart, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(relatorioVoltar2)
                .addContainerGap())
        );

        relatorioMesTab.addTab("tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(relatorioMesTab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(relatorioMesTab)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> relatorioCategoriaCb;
    private javax.swing.JComboBox<String> relatorioCategoriaMesCb;
    private javax.swing.JComboBox<String> relatorioMesFinalCb;
    private javax.swing.JComboBox<String> relatorioMesInicialCb;
    private javax.swing.JTabbedPane relatorioMesTab;
    private javax.swing.JButton relatorioVoltar;
    private javax.swing.JButton relatorioVoltar2;
    private javax.swing.JPanel viewRelatorio_Bar;
    private javax.swing.JLayeredPane viewRelatorio_BarChart;
    private javax.swing.JPanel viewRelatorio_Pie;
    private javax.swing.JLayeredPane viewRelatorio_PieChart;
    // End of variables declaration//GEN-END:variables

/**
     * Creates a sample dataset 
     */
    
    //Adicionei o int mes para passar o mes dos dados.
                                        
    private  PieDataset createPieDataset(int mes) {
        
        
        //Exemplo da minha ideia
        
        //For (categorias)
        // result.setValue(categoria[i].getName(), bd.GetGastosComida(mes));
        
        //Creio que essa funcao vai ser utilizada pelo controlador... Nao sei se este modo vai se encaixar bem na arquitetura...
        
        
        DefaultPieDataset result = new DefaultPieDataset();
        result.setValue("Gasolina", 290);
        result.setValue("Festas", 1500);
        result.setValue("St Tecla", 750);
        result.setValue("XUXUs", 1700);
        return result;
        
    }
    
    public void geraPieChart(int mes){
        
        PieDataset dataset = createPieDataset(mes);
        JFreeChart chart = createChart("Relatorio", dataset);  
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension( 339, 117) );        
        //chartPanel.setSize(315,125);
        
        viewRelatorio_PieChart.removeAll();
        viewRelatorio_PieChart.add(chartPanel, BorderLayout.CENTER);
        viewRelatorio_PieChart.validate();

    }
    
    public void geraBarChart(){
    
        JFreeChart barChart = ChartFactory.createBarChart(
            "Relatório Geral",           
            "",            
            "R$",            
            createBarDataset(),          
            org.jfree.chart.plot.PlotOrientation.VERTICAL,           
            true, true, false);
      
      
        ChartPanel chartPanel = new ChartPanel( barChart );        
        chartPanel.setPreferredSize(new java.awt.Dimension(339, 117));        
     
       
        //chartPanel.setSize(315,125);
        
        viewRelatorio_BarChart.removeAll();
        viewRelatorio_BarChart.add(chartPanel, BorderLayout.CENTER);
        viewRelatorio_BarChart.validate();

    }
        
    private CategoryDataset createBarDataset() {
      final String Comida = "Comida";        
      final String Xuxus = "Xuxus";        
      final String STecla = "Santa Tecla";        
      final String Baiuca = "Baiuca";        
      final String Receita = "Receita";        
      final String Despesa = "Despesa";    
      final DefaultCategoryDataset dataset = 
      new DefaultCategoryDataset( );  

        dataset.addValue( 111.0, "Total de Despesas" , "Jan/2016");
        dataset.addValue( 156.0, "Total de Receitas" , "Jan/2016");
       // dataset.addValue( 200.0 , Comida , Receita );    
     //   dataset.addValue( 3.0 , fiat , userrating );        
        //dataset.addValue( 5.0 , fiat , millage ); 
       // dataset.addValue( 5.0 , fiat , safety );           

        dataset.addValue( 52.0, "Total de Despesas" , "Fev/2016");
        dataset.addValue( 62.0, "Total de Receitas" , "Fev/2016");
        
        dataset.addValue( 32.0, "Total de Despesas" , "Abr/2016");
        dataset.addValue( 24.0, "Total de Receitas" , "Abr/2016");        
        //dataset.addValue( 6.0 , audi , userrating );       
        //dataset.addValue( 10.0 , audi , millage );        
       // dataset.addValue( 4.0 , audi , safety );

//        dataset.addValue( 400.0 , STecla , Receita );        
        //dataset.addValue( 2.0 , ford , userrating );        
        //dataset.addValue( 3.0 , ford , millage );        
        //dataset.addValue( 6.0 , ford , safety );               

      return dataset; 
   }
    
/**
     * Creates a chart
     */
//Essa funcao pode ser usada para personlizar mais ou atualizar o chart.
    //OBS: nao esta sendo usada no chart criado na funcao geraChart
    
    private JFreeChart createChart(String title, PieDataset dataset ) {
        
        JFreeChart chart = ChartFactory.createPieChart3D(title,          // chart title
            dataset,                // data
            true,                   // include legend
            true,
            false);

        PiePlot3D plot = (PiePlot3D) chart.getPlot();
        plot.setStartAngle(290);
        plot.setDirection(Rotation.CLOCKWISE);
        plot.setForegroundAlpha(0.5f);
        return chart;
        
    }


}
